export const STAGE = {
	SCHEDULED: 100,
	REVIEW: 101,
	REJECTED: 102,
	CANCELED: 103,
	CONFIRMED: 104,
}

export const REASON_TYPE = {
	CANCEL_SCHEDULED_INSPECTION: "CANCEL_SCHEDULED_INSPECTION",
	REJECT_INSPECTION: "REJECT_INSPECTION"
}


export const PO_DETAIL_STATUS = {
	RELEASED_INSPECTION: 222,
	INSPECTION_NOT_REQUIRED: 224,
	PENDING_INSPECTION: 223,
	REJECTED_INSPECTION: 27,
	APPROVED_INSPECTION: 26,
}


export const INSPECTION_STAGE_CODE = {
  APPROVED: "1001",
  REJECT: "1002",
  PENDING: "1003",
  APPROVED_WITH_OBSERVATIONS: "1004",
  ON_HOLD: "1005",
  IN_PROGRESS: "1006"
}
